# Numpy Questions
**Import the numpy package under the name np and Print the numpy version and the configuration **



In [2]:
import numpy as np

In [2]:
print(np.__version__)

1.19.5


In [3]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


**2. Create a null vector of size 10**

In [5]:
import numpy as np

In [6]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**3. Create Simple 1-D array and check type and check data types in array**

In [7]:
arr = np.array([1, 2, 3, 4, 5, 600])

In [8]:
print('Array:', arr)
  
print('Datatype:', arr.dtype)

Array: [  1   2   3   4   5 600]
Datatype: int32


**4. How to find number of dimensions, bytes per element and bytes of memory used?**


**bytes of memory used**

In [18]:
print(arr.nbytes)

24


***dimension***

In [16]:
print(arr.ndim)

1


**bytes per element**

In [17]:
print(arr.itemsize)

4


**5. Create a null vector of size 10 but the fifth value which is 1**

In [19]:
x=np.zeros(10)
x[4]=1

In [20]:
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**6. Create a vector with values ranging from 10 to 49**

In [21]:
vector = np.arange(10,49)

In [22]:
print("Original vector:", vector)

Original vector: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


**7. Reverse a vector (first element becomes last)**

In [23]:
res = vector[::-1]

In [24]:
print(res)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**8. Create a 3x3 matrix with values ranging from 0 to 8**

In [25]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**9. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [26]:
arr1 = np.array([1,2,0,0,4,0])

In [28]:
np.nonzero(arr1)

(array([0, 1, 4], dtype=int64),)

**10. Create a 3x3 identity matrix**

In [29]:
identity_matrix=np.identity(3)

In [32]:
print("Identity Matrix: \n",identity_matrix)

Identity Matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**11. Create a 3x3x3 array with random values**

In [34]:
rnd = np.random.random((3,3,3))

In [35]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**12. Create a 10x10 array with random values and find the minimum and maximum values**

In [37]:
y = np.random.random((10,10))

In [38]:
ymin, ymax = y.min(), y.max()

In [39]:
print(y)

[[0.77558194 0.9077484  0.40692576 0.89689909 0.54326505 0.060516
  0.35896887 0.81133811 0.27712052 0.93585948]
 [0.70838561 0.90289766 0.5696577  0.24072619 0.72463352 0.68675506
  0.42256707 0.57399592 0.24088607 0.77968774]
 [0.258086   0.66407133 0.91451724 0.96272437 0.03765141 0.19612397
  0.04863249 0.47032578 0.22983588 0.52140211]
 [0.20882267 0.00178489 0.61089733 0.18250817 0.42349201 0.11958934
  0.00307906 0.98927364 0.33451984 0.34665379]
 [0.2282833  0.16129999 0.18696493 0.55250563 0.01062793 0.30410783
  0.0642549  0.76312014 0.84229516 0.94784803]
 [0.65478416 0.61164824 0.19891509 0.16687022 0.49970337 0.93036858
  0.96565513 0.38373441 0.11623775 0.24886097]
 [0.99522846 0.28462657 0.92004032 0.88157369 0.32747881 0.24148927
  0.49675947 0.86994502 0.49180929 0.6220665 ]
 [0.28564912 0.33543973 0.94357308 0.86411005 0.86895317 0.01818704
  0.55932764 0.72879158 0.64799704 0.66842232]
 [0.31139669 0.41746383 0.19689325 0.28274551 0.66530347 0.88458534
  0.83446896 0

In [40]:
print(ymin, ymax)

0.0017848933234855258 0.9952284634469685


**13. Create a random vector of size 30 and find the mean value**

In [43]:
z = np.random.random(30)
print("Original vector: \n",z)

Original vector: 
 [0.61572429 0.30864521 0.09174358 0.83871816 0.14572985 0.93479798
 0.84761832 0.85398242 0.44850049 0.88005386 0.11634965 0.21839776
 0.19935235 0.24799353 0.10207229 0.29061588 0.14006944 0.99901715
 0.90536088 0.99606086 0.07703694 0.98132773 0.64852605 0.29830601
 0.79001933 0.34494399 0.35896785 0.26626    0.75752216 0.37391105]


In [44]:
a=np.mean(z)

In [45]:
print("Mean:\n",a)

Mean:
 0.5025875022776188


**14. Create a 2d array with 1 on the border and 0 inside**

In [46]:
k = np.ones((5,5))
print("Original array: \n",k)

Original array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
k[1:-1,1:-1] = 0

In [48]:
print("1 on the border and 0 inside--> \n",k)

1 on the border and 0 inside--> 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**15. How to add a border (filled with 0's) around an existing array?**

In [50]:
l = np.ones((3,3))

In [51]:
print("Original array:",l)

Original array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
l = np.pad(l, pad_width=1, mode='constant', constant_values=0)
print("new array: \n",l)

new array: 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?**

In [55]:
p=np.array([[ 1,2, 3, 4, 5, 6, 7],[ 8, 9, 10, 11, 12, 13, 14]])

**get first row**

In [56]:
p[0]

array([1, 2, 3, 4, 5, 6, 7])

**get 3rd column**

In [57]:
 p[:, 2]

array([ 3, 10])

**get 13**

In [58]:
p[1,5]

13

**get [2, 4, 6]**

In [66]:
print("get[2,4,6]-->",p[0,1],p[0,3],p[0,5])

get[2,4,6]--> 2 4 6


**replace 13 by 20**

In [67]:
p[1,5] =20
p[1,5]

20

**17. How to Convert a 1D array to a 2D array with 2 rows**

In [70]:
m = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("original:\n",m)
arr_2d = np.reshape(m, (2, 5))
print("2d array:\n",arr_2d)

original:
 [0 1 2 3 4 5 6 7 8 9]
2d array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


 **18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.**

**Input:**

**a = np.array([1,2,3])**`
**Desired Output:**

** array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])**

In [7]:
c = np.array([1,2,3])
d = np.array([3,3,3])
print("array:\n",np.repeat(c, d))

array:
 [1 1 1 2 2 2 3 3 3]


**19. Write a program to show how Numpy taking less memory compared to Python List?**

In [8]:
import time 
import sys

In [9]:
array = np.arange(100)
print("Size of NumPy array: ", array.itemsize * array.itemsize)

Size of NumPy array:  16


In [10]:
list = range(0, 10)
print("Size of list: ", sys.getsizeof(1)*len(list))

Size of list:  280


**20. Write a program to show how Numpy taking less time compared to Python List?**

In [12]:
Size = 100000

list1 = range(Size)
list2 = range(Size)

arr2 = np.arange(Size)
arr3 = np.arange(Size)

start = time.time()
result = [(x, y) for x, y in zip(list1, list2)]
          
print("Time for Python List in msec: ", (time.time() - start) * 1000)


Time for Python List in msec:  33.94651412963867


In [15]:
start = time.time()
result = arr2,   arr3
print("Time for NumPy array in msec: ", (time.time()- start) * 1000)


Time for NumPy array in msec:  5.01561164855957
